/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconBasilTwitterOutline: typeof import('~icons/basil/twitter-outline.jsx')['default']
  const IconBiSubstack: typeof import('~icons/bi/substack.jsx')['default']
  const IconFeGithub: typeof import('~icons/fe/github.jsx')['default']
  const IconHeroiconsCalendar: typeof import('~icons/heroicons/calendar.jsx')['default']
  const IconHeroiconsEnvelope: typeof import('~icons/heroicons/envelope.jsx')['default']
}
